defaults:
  - task: misspecified_likelihood
  - inference: npe
  - metric: ppc
  - _self_

metrics_sweep: "c2st, ppc"

random_seed: 86
postprocess: true

hydra:
  mode: MULTIRUN
  sweeper:
    params: 
      metric: ${metrics_sweep} 
      inference.num_simulations: ${inference.num_simulations}

  callbacks:
    postprocess:
      _target_: src.utils.postprocess_callback.PostProcessCallback