defaults:
  - task: misspecified_likelihood
  - inference: npe
  - metric: c2st
  - _self_

random_seed: 86
postprocess: true

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      task: misspecified_likelihood,other_task
      inference: npe,nle
      inference.num_simulations: 100,1000

  callbacks:
    postprocess:
      _target_: src.utils.postprocess_callback.PostProcessCallback