defaults:
  - task: misspecified_likelihood
  - inference: npe
  - metric: c2st
  - _self_

random_seed: 86
postprocess: true

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      inference.num_simulations: ${inference.num_simulations}

  callbacks:
    postprocess:
      _target_: src.utils.postprocess_callback.PostProcessCallback