defaults:
  - task: misspecified_likelihood
  - inference: npe
  - metric: ppc
  - _self_

random_seed: 86
postprocess: true

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      task.tau_m: ${task.tau_m}
      task.lambda_val: ${task.lambda_val}
      inference.num_simulations: ${inference.num_simulations}

  callbacks:
    postprocess:
      _target_: src.utils.postprocess_callback.PostProcessCallback