defaults:
  - task: misspecified_likelihood
  - inference: npe
  - metric: ppc
  - _self_

random_seed: 86

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      inference.num_simulations: ${inference.num_simulations}